# Lesson 5 Questions

In [2]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

#Here we are importing necessary libraries

In [83]:
#Question 1

#PART A

#An array of strings is defined, then each element is changed to upper changes and displayed
q1=make_array(['Alpha','Bravo','Charlie','Delta'])
q1_Upper=np.char.upper(q1)
print(q1_Upper)

#PART B

#The number of times the character 'a' appears in each element of the array, and is printed in the form of an array
q1_aCount=np.char.count(q1_Upper,'A')
print(q1_aCount)

#PART C

#The len() function is vectorized, and applied to all elements of the array. The length of each element in the array is printed
lengthCalc=np.vectorize(len)
print(lengthCalc(q1))

[['ALPHA' 'BRAVO' 'CHARLIE' 'DELTA']]
[[2 1 1 1]]
[[5 5 7 5]]


In [3]:
#Question 2

#Array is defined as every other odd number from 1 to 41 inclusive
oddArr=np.arange(1,42,4)
print(oddArr)

#PART A

#Sum of array is found using np.sum()
oddSum=np.sum(oddArr)
print('Sum is: '+str(oddSum))


#Product of array is found using np.prod(), needed to convert to float due to max integer issues
oddFloat=oddArr.astype(float)
oddProd=np.prod(oddFloat)
print('Product is: '+str(oddProd))

#PART B

#The natural log of each element in the array is found using np.log()
oddLn=np.log(oddArr)
print(oddLn)


[ 1  5  9 13 17 21 25 29 33 37 41]
Sum is: 231
Product is: 7.57986742013e+12
[ 0.          1.60943791  2.19722458  2.56494936  2.83321334  3.04452244
  3.21887582  3.36729583  3.49650756  3.61091791  3.71357207]
